# Generated by Django 2.0.3 on 2018-04-03 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.ProductDepartment')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSpecialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kosher', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('organic', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('grain_free', models.BooleanField(default=False)),
                ('lactose_free', models.BooleanField(default=False)),
                ('low_carb', models.BooleanField(default=False)),
                ('low_fat', models.BooleanField(default=False)),
                ('sugar_free', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kilo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='store_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_description',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_kilo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='productstore',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Product'),
        ),
        migrations.AddField(
            model_name='productstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Store'),
        ),
        migrations.AddField(
            model_name='productspecialty',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ProductDepartment'),
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(through='food.ProductStore', to='food.Product'),
        ),
    ]
