# Generated by Django 2.0.3 on 2018-04-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180403_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdepartment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.ProductDepartment'),
        ),
    ]
