# Generated by Django 2.0.3 on 2018-04-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://s3.amazonaws.com/nadaj-food/product_images/No_Image_Available.gif', max_length=2083),
        ),
    ]
