# Generated by Django 2.0.3 on 2018-04-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180408_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecialty',
            name='keto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productspecialty',
            name='paleo',
            field=models.BooleanField(default=False),
        ),
    ]
