# Generated by Django 2.0.3 on 2018-04-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20180411_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecialty',
            old_name='lactose_free',
            new_name='dairy_free',
        ),
    ]
