# Generated by Django 2.0.3 on 2018-04-11 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_productspecialty_low_carb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecialty',
            name='grain_free',
        ),
    ]
