# Generated by Django 2.0.3 on 2018-04-12 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_remove_productspecialty_grain_free'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productstore',
            unique_together={('product', 'store')},
        ),
    ]
