# Generated by Django 2.0.3 on 2018-04-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20180412_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.CharField(default='https://s3.amazonaws.com/nadaj-food/store_images/No_Image_Available.gif', max_length=2083),
        ),
    ]
