# Generated by Django 2.0.3 on 2018-04-15 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_product_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
    ]
