# Generated by Django 2.0.3 on 2018-04-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_remove_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(through='food.ProductStore', to='food.Store'),
        ),
    ]
