# Generated by Django 2.0.3 on 2018-04-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_auto_20180418_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='location',
            name='city',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
