# Generated by Django 2.0.3 on 2018-04-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0023_LocationStore'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.State')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
